# ===== AUTO-GENERATED BY APP-KIT - DO NOT EDIT =====
# This file is managed by @mchen-lab/app-kit and will be
# overwritten when running `npx @mchen-lab/app-kit update`.
# Version: 0.1.7
# ====================================================

FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./

# Copy local libs
COPY libs ./libs

# Install all dependencies
RUN npm ci

# Copy source files
COPY . .

# Build arguments
ARG GIT_COMMIT
ARG BUILD_METADATA

# Set environment variables for build
ENV GIT_COMMIT=${GIT_COMMIT}
ENV BUILD_METADATA=${BUILD_METADATA}

# Build frontend (if exists)
RUN npm run build:frontend || echo "No frontend build"
RUN mkdir -p dist

# Build server
RUN npm run build:server

# Production stage
FROM node:20-alpine AS production

# Architecture support
ARG TARGETARCH

# Install basic tools and GOST
RUN apk add --no-cache ca-certificates curl && \
    case "${TARGETARCH}" in \
        "amd64") GOST_ARCH="linux_amd64" ;; \
        "arm64") GOST_ARCH="linux_arm64" ;; \
        *) echo "Unsupported architecture: ${TARGETARCH}"; exit 1 ;; \
    esac && \
    curl -L "https://github.com/go-gost/gost/releases/download/v3.2.6/gost_3.2.6_${GOST_ARCH}.tar.gz" -o gost.tar.gz && \
    tar -xzf gost.tar.gz && \
    mv gost /usr/local/bin/gost && \
    chmod +x /usr/local/bin/gost && \
    rm gost.tar.gz README.md LICENSE

WORKDIR /app

# Create directories for persistence
RUN mkdir -p /app/data /app/logs && chmod 777 /app/data /app/logs

# Copy package files
COPY package*.json ./

# Copy local libs for production install
COPY libs ./libs

# Install only production dependencies
RUN npm ci --only=production && \
    # Clean up caches to reduce image size
    rm -rf /root/.cache && \
    rm -rf /root/.npm

# Copy built assets from builder
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/dist-server ./dist-server

# Expose port
EXPOSE 31130

# Set environment variables
ENV NODE_ENV=production
ENV PORT=31130
ENV DATA_DIR=/app/data
ENV LOGS_DIR=/app/logs
# Also pass build info to production for runtime API
ARG GIT_COMMIT
ARG BUILD_METADATA
ENV GIT_COMMIT=${GIT_COMMIT}
ENV BUILD_METADATA=${BUILD_METADATA}
ENV VITE_COMMIT_HASH=${GIT_COMMIT}
ENV VITE_APP_VERSION=${BUILD_METADATA}

# Start the server
CMD ["node", "dist-server/server/index.js"]
