# ===== AUTO-GENERATED BY APP-KIT - DO NOT EDIT =====
# This file is managed by @mchen-lab/app-kit and will be
# overwritten when running `npx @mchen-lab/app-kit update`.
# Version: 0.1.6
# ====================================================

FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./

# Copy local libs
COPY libs ./libs

# Install all dependencies
RUN npm ci

# Copy source files
COPY . .

# Build arguments
ARG GIT_COMMIT
ARG BUILD_METADATA

# Set environment variables for build
ENV GIT_COMMIT=${GIT_COMMIT}
ENV BUILD_METADATA=${BUILD_METADATA}

# Build frontend (if exists)
RUN npm run build:frontend || echo "No frontend build"
RUN mkdir -p dist

# Build server
RUN npm run build:server

# Production stage
FROM node:20-alpine AS production

# Install basic tools
RUN apk add --no-cache ca-certificates

WORKDIR /app

# Create data directory for persistence
RUN mkdir -p /app/data && chmod 777 /app/data

# Copy package files
COPY package*.json ./

# Copy local libs for production install
COPY libs ./libs

# Install only production dependencies
RUN npm ci --only=production

# Copy built assets from builder
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/dist-server ./dist-server

# Expose port
EXPOSE 31131

# Set environment variables
ENV NODE_ENV=production
ENV PORT=31131
# Also pass build info to production for runtime API
ARG GIT_COMMIT
ARG BUILD_METADATA
ENV GIT_COMMIT=${GIT_COMMIT}
ENV BUILD_METADATA=${BUILD_METADATA}

# Start the server
CMD ["node", "dist-server/server/index.js"]
