# ===== AUTO-GENERATED BY APP-KIT - DO NOT EDIT =====
# This file is managed by @mchen-lab/app-kit and will be
# overwritten when running `npx @mchen-lab/app-kit update`.
# Version: 0.1.6
# ====================================================

FROM node:20-alpine AS builder

WORKDIR /app

# Copy package files
COPY package*.json ./

# Copy local libs
COPY libs ./libs

# Install all dependencies
RUN npm ci

# Copy source files
COPY . .

# Build arguments
ARG GIT_COMMIT
ARG BUILD_METADATA

# Set environment variables for build
ENV GIT_COMMIT=${GIT_COMMIT}
ENV BUILD_METADATA=${BUILD_METADATA}

# Build frontend (if exists)
RUN npm run build:frontend || echo "No frontend build"
RUN mkdir -p dist

# Build server
RUN npm run build:server

# Production stage
FROM node:20-alpine AS production

# Install basic tools and GOST
RUN apk add --no-cache ca-certificates curl tar

# Download and install GOST v3
# We use the official binary for linux/amd64 (or match alpine's architecture)
RUN curl -L https://github.com/go-gost/gost/releases/download/v3.0.0-rc.10/gost_3.0.0-rc.10_linux_amd64.tar.gz | tar -xz && \
    mv gost /usr/local/bin/gost && \
    chmod +x /usr/local/bin/gost

WORKDIR /app

# Create data directory for persistence
RUN mkdir -p /app/data && chmod 777 /app/data

# Copy package files
COPY package*.json ./

# Copy local libs for production install
COPY libs ./libs

# Install only production dependencies
RUN npm ci --only=production

# Copy built assets from builder
COPY --from=builder /app/dist ./dist
COPY --from=builder /app/dist-server ./dist-server

# Expose all three ports
EXPOSE 31130 31131 31132

# Set environment variables
ENV NODE_ENV=production
ENV PORT=31130
ENV GOST_API_URL=http://127.0.0.1:31132
ENV GOST_PROXY_URL=http://127.0.0.1:31131
ENV GOST_BINARY_PATH=/usr/local/bin/gost

# Also pass build info to production for runtime API
ARG GIT_COMMIT
ARG BUILD_METADATA
ENV GIT_COMMIT=${GIT_COMMIT}
ENV BUILD_METADATA=${BUILD_METADATA}

# Start the server
CMD ["node", "dist-server/server/index.js"]
