# ===== AUTO-GENERATED BY APP-KIT - DO NOT EDIT =====
# This file is managed by @mchen-lab/app-kit and will be
# overwritten when running `npx @mchen-lab/app-kit update`.
# Version: 0.1.6
# ====================================================

#!/bin/bash

# Get the absolute path of the project root
PROJECT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Check if node_modules exists (dependencies installed)
if [ ! -d "$PROJECT_ROOT/node_modules" ]; then
    echo "❌ Error: node_modules not found. Please run 'npm install' from the root directory first."
    exit 1
fi

# Function to backup existing log file
backup_log() {
    local log_file=$1
    local log_name=$2

    if [ -f "$log_file" ]; then
        if [ -f "${log_file}.bak" ]; then
            echo "Overwriting existing $log_name backup and creating new backup: ${log_file}.bak"
        else
            echo "Backing up existing $log_name log to ${log_file}.bak"
        fi
        mv "$log_file" "${log_file}.bak"
    fi
}

# Function to kill process on a specific port
kill_port() {
    local port=$1
    local process_name=$2

    echo "Checking for existing $process_name processes on port $port..."
    
    # use lsof to get PIDs - only target the listener to avoid conflicts with persistent client connections (e.g. Chrome)
    local pids=$(lsof -nP -i :$port -sTCP:LISTEN -t 2>/dev/null)
    
    if [ ! -z "$pids" ]; then
        # Iterate through PIDs to check their command name
        local target_pids=""
        for pid in $pids; do
            # Get the command name for the PID
            local cmd=$(ps -p $pid -o comm= 2>/dev/null)
            # Check if command is node-related (basename)
            local cmd_base=$(basename "$cmd" 2>/dev/null)
            
            if [[ "$cmd_base" == "node" ]]; then
                target_pids="$target_pids $pid"
            else
                echo "⚠️  Warning: Process '$cmd' (PID: $pid) is using port $port. NOT killing it as it does not appear to be our server."
                echo "   maybe a docker version is already running"
                return 1
            fi
        done

        if [ ! -z "$target_pids" ]; then
            echo "Found existing node process(es) (PIDs:$target_pids). Killing..."
            echo "$target_pids" | xargs kill -9 2>/dev/null || true
            sleep 2
            
            # Verify they are killed
            local remaining_pids=$(lsof -ti :$port -sTCP:LISTEN 2>/dev/null)
            if [ ! -z "$remaining_pids" ]; then
                echo "⚠️  Warning: Port $port may still be in use."
            else
                echo "✅ Successfully killed node processes on port $port."
            fi
        fi
    else
        # Fallback checks only if port was empty
        echo "No process found directly binding port $port."
        
        # We can keep the specific pattern matches as a secondary cleanup sweep
        # just in case the port wasn't bound yet but the process exists
        local cleanup_pids=""
        cleanup_pids=$(pgrep -f "workspace=$process_name" 2>/dev/null || true)
        
        if [ ! -z "$cleanup_pids" ]; then
             echo "Cleaning up loose workspace processes: $cleanup_pids"
             echo "$cleanup_pids" | xargs kill -9 2>/dev/null || true
        fi
    fi
}

start_server() {
    echo "🚀 Starting gost-proxy-service on port 31130..."

    # Ensure logs/servers directory exists
    mkdir -p "$PROJECT_ROOT/logs"

    # Backup existing server log
    backup_log "$PROJECT_ROOT/logs/server.log" "server"

    # Start server with watch mode enabled
    cd "$PROJECT_ROOT"
    # Use native Node watch mode with tsx for TypeScript support
    # --watch-path src ensures we ONLY restart when source code changes
    node --import tsx --watch --watch-path src src/server/index.ts >> "$PROJECT_ROOT/logs/server.log" 2>&1 &
    SERVER_PID=$!
    echo "✅ Server started with PID: $SERVER_PID"
    echo "📝 Server logs: $PROJECT_ROOT/logs/server.log"
}

# Trap function to kill processes
cleanup() {
    echo ""
    echo "Cleaning up..."
    if [ ! -z "$TAIL_PID" ]; then
        kill $TAIL_PID 2>/dev/null
    fi
    if [ ! -z "$SERVER_PID" ]; then
        echo "Killing server process $SERVER_PID"
        kill $SERVER_PID 2>/dev/null
    fi
    # Also attempt to kill by port as a fallback
    kill_port 31130 "server"
    exit 0
}

trap cleanup INT TERM EXIT

echo "🛑 Stopping any existing gost-proxy-service server..."
if ! kill_port 31130 "server"; then
    echo "❌ restart aborted."
    exit 1
fi

echo ""
echo "🧹 Cleaning previous build artifacts..."
if [ -d "$PROJECT_ROOT/dist" ]; then
    echo "   Removing dist directory to force dev mode..."
    rm -rf "$PROJECT_ROOT/dist"
    echo "   ✅ Cleaned dist"
fi

echo "🎯 Starting gost-proxy-service..."
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
start_server

echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "✅ gost-proxy-service is running!"
echo ""
echo "📍 Services:"
echo "   • Web UI & API: http://localhost:31130"
echo ""
echo "Press Ctrl+C to stop"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

# Tail the logs to keep the script running and show output
echo "📋 Tailing logs (Ctrl+C to stop)..."
tail -f "$PROJECT_ROOT/logs/server.log" &
TAIL_PID=$!

wait $TAIL_PID
